# -*- coding: utf-8 -*-
# Deployment settings for c:\marmalade\7.0\quick\target\win\quick_prebuilt.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/7.0/s3e/makefile_builder/mkb.py', 'c:/Users/Daniel/Documents/Quick/Projects/Flappy Bird/Flappy Bird.mkb', '--deploy-only', '--hub-data', 'C:/Users/Daniel/Documents/Quick/Projects/Flappy Bird/project_Flappy Bird/mkb-quick.txt', '--buildenv=QUICK', '--use-prebuilt']
mkb = 'c:/Users/Daniel/Documents/Quick/Projects/Flappy Bird/Flappy Bird.mkb'
mkf = ['c:\\marmalade\\7.0\\quick\\quick_prebuilt.mkf', 'c:\\marmalade\\7.0\\quick\\quick_prebuilt_options.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/Daniel/Documents/Quick/Projects/Flappy Bird/resources', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'Happy Bird'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'Happy Bird'
    long_caption = 'Happy Bird'
    version = [0, 0, 1]
    config = ['c:/Users/Daniel/Documents/Quick/Projects/Flappy Bird/resources/common.icf', 'c:/Users/Daniel/Documents/Quick/Projects/Flappy Bird/resources/app.icf']
    data_dir = 'c:/Users/Daniel/Documents/Quick/Projects/Flappy Bird/resources'
    iphone_link_lib = ['s3eFacebook', 's3eIOSAppStoreBilling', 's3eIOSGameCenter', 's3eWebView', 's3eFlurry', 'FlurryAnalytics']
    wp8_ext_managed_dll = []
    linux_ext_lib = []
    android_extra_application_manifest = []
    iphone_link_libdir = ['c:/marmalade/7.0/extensions/s3eFacebook/lib/iphone', 'c:/marmalade/7.0/extensions/s3eIOSAppStoreBilling/lib/iphone', 'c:/marmalade/7.0/extensions/s3eIOSGameCenter/lib/iphone', 'c:/marmalade/7.0/extensions/s3eWebView/lib/iphone', 'c:/marmalade/7.0/extensions/s3eFlurry/lib/iphone']
    iphone_link_libdirs = []
    iphone_link_opts = ['-F$MARMALADE_ROOT/extensions/s3eFacebook/source/iphone/facebook-ios-sdk -framework FacebookSDK -weak_framework AdSupport -weak_framework Accounts -weak_framework Social -lsqlite3']
    provider = 'Daniel Williamson'
    android_external_jars = ['c:/marmalade/7.0/extensions/s3eFacebook/lib/android/s3eFacebook.jar', 'c:/marmalade/7.0/extensions/s3eAndroidMarketBilling/lib/android/s3eAndroidMarketBilling.jar', 'c:/marmalade/7.0/extensions/s3eFlurry/lib/android/s3eFlurry.jar', 'c:/marmalade/7.0/extensions/s3eFlurry/lib/android/FlurryAgent.jar', 'c:/marmalade/7.0/extensions/s3eWebView/lib/android/s3eWebView.jar']
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    wp8_ext_native_dll = []
    splashscreen_auto_onblack = 0
    win32_ext_dll = ['c:/marmalade/7.0/extensions/s3eWebView/lib/win32/s3eWebView.dll']
    android_so = ['c:/marmalade/7.0/extensions/s3eFacebook/lib/android/libs3eFacebook.so', 'c:/marmalade/7.0/extensions/s3eAndroidMarketBilling/lib/android/libs3eAndroidMarketBilling.so', 'c:/marmalade/7.0/extensions/s3eFlurry/lib/android/libs3eFlurry.so', 'c:/marmalade/7.0/extensions/s3eWebView/lib/android/libs3eWebView.so']
    osx_ext_dll = ['c:/marmalade/7.0/extensions/s3eWebView/lib/osx/libs3eWebView.dylib']
    tizen_so = []
    wp8_ext_capabilities = []
    iphone_enable_4inch_retina = 1
    blackberry_author = 'Daniel Williamson'
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:\marmalade\7.0\quick\target\notavailable\quick_prebuilt_d.so',
                   'release' : r'c:\marmalade\7.0\quick\target\notavailable\quick_prebuilt.so',
                 },
         'wp8-arm' : {
                   'debug'   : r'c:\marmalade\7.0\quick\target\wp8\arm\quick_prebuilt_d.s86',
                   'release' : r'c:\marmalade\7.0\quick\target\wp8\arm\quick_prebuilt.s86',
                 },
         'wp8-x86' : {
                   'debug'   : r'c:\marmalade\7.0\quick\target\wp8\x86\quick_prebuilt_d.s86',
                   'release' : r'c:\marmalade\7.0\quick\target\wp8\x86\quick_prebuilt.s86',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:\marmalade\7.0\quick\target\mips\quick_prebuilt_d.so',
                   'release' : r'c:\marmalade\7.0\quick\target\mips\quick_prebuilt.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:\marmalade\7.0\quick\target\arm\quick_prebuilt_d.s3e',
                   'release' : r'c:\marmalade\7.0\quick\target\arm\quick_prebuilt.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:\marmalade\7.0\quick\target\notavailable\quick_prebuilt_d.so',
                   'release' : r'c:\marmalade\7.0\quick\target\notavailable\quick_prebuilt.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:\marmalade\7.0\quick\target\x86\quick_prebuilt_d.so',
                   'release' : r'c:\marmalade\7.0\quick\target\x86\quick_prebuilt.so',
                 },
         'arm' : {
                   'debug'   : r'c:\marmalade\7.0\quick\target\arm\quick_prebuilt_d.s3e',
                   'release' : r'c:\marmalade\7.0\quick\target\arm\quick_prebuilt.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:\marmalade\7.0\quick\target\win\quick_prebuilt_d.s86',
                   'release' : r'c:\marmalade\7.0\quick\target\win\quick_prebuilt.s86',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()

######### Configuration: Windows

c = DeployConfig()
config['Windows'] = c
c.os = ['win32']
c.arch = ['x86']
c.target_folder = 'Windows'

######### Configuration: Mac OS X

c = DeployConfig()
config['Mac OS X'] = c
c.os = ['osx']
c.arch = ['x86']
c.target_folder = 'Mac OS X'
